### PR TITLE
Have LFC generate a main function that can optionally be included

### PR DESCRIPTION
**Pull request by erlingrj**
Also, build Zephyr and RIOT LF example in CI

### CODE REVIEW

**Comment by erlingrj** [comment]
@LasseRosenow, can you see why the RIOT build systems fails to include `lf_main.c` even though I explicitly list it as a source in `riot.mk`?

**Comment by LasseRosenow** [comment]
> @LasseRosenow, can you see why the RIOT build systems fails to include `lf_main.c` even though I explicitly list it as a source in `riot.mk`?

I will look at it when I have time later this evening

**Comment by LasseRosenow** [comment]
There must be a CI specific issue, I was able to build it on my machine :O

**Comment by LasseRosenow** [comment]
Ooooohhhh actually I remember why. The problem is in the CI we are currently using riot 2024.07.

Adding c files in folders using SRC += is new since a few weeks ago. Sadly it didn't even make it into RIOT 2024.10.

So we should maybe switch the ci to a specific commit in the master branch for now?

**Comment by LasseRosenow** [comment]
Yay it works now 🥳

**Comment by erlingrj** [comment]
Great! Thank you :100:

**Pull request merged**
